import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Animation novu blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black w-full h-screen p-8 text-white text-4xl ">
        <div className="flex flex-wrap">
          {[...Array(546)].map(_ => <span className="px-2 telm">novu</span>)}

        </div>
      </main>


    </div>
  )
}

